# Archivo para definir como crear y correr la API en Kubernetes usando un Deployment

# Deployment = Recurso de Kubernetes para aplicaciones sin estado, permite escalar y reemplazar pods automáticamente

# apiVersion = Versión de la API de Kubernetes que es apps/v1
# kind = Tipo de recurso que se va a crear, en este caso un Deployment
# metadata = Información descriptiva del recurso, como nombre y namespace

# spec = Especificaciones del Deployment
# replicas = Numero de copias de la API que se quieren correr, en este caso 2 (escalamiento horizontal)
# selector = Como identificar los pods que pertenecen a este Deployment usando labels (app: main-api)

# template = Plantilla para los pods que se van a crear
# metadata = Información descriptiva del pod, se le asigna la etiqueta app: main-api

# spec = Especificaciones del pod
# containers = Lista de contenedores, en este caso uno llamado main-api
# image = Imagen de Docker que se va a usar para correr la API
# imagePullPolicy = Never indica que Kubernetes use la imagen local y no la descargue de internet

# ports = Puerto expuesto por el contenedor (8000 donde corre FastAPI)

# envFrom = Permite cargar variables de entorno desde:
# configMapRef = Variables no sensibles (configuración general)
# secretRef = Variables sensibles (credenciales, llaves, passwords)

# resources = Define la cantidad de CPU y memoria que el contenedor puede usar

# requests = Recursos mínimos que Kubernetes reserva para el pod
# memory = Cantidad mínima de memoria RAM (128Mi)
# cpu = Cantidad mínima de CPU (100m = 0.1 CPU)

# limits = Recursos máximos que el pod puede consumir
# memory = Máximo de memoria RAM permitido (256Mi)
# cpu = Máximo de CPU permitido (500m = 0.5 CPU)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-api
  namespace: reservainteligente
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-api
  template:
    metadata:
      labels:
        app: main-api
    spec:
      containers:
        - name: main-api
          image: reservainteligente-api:v3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret