apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: reservainteligente
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
        - name: airflow-scheduler
          image: ghcr.io/chris124v/reserva_inteligente-airflow:latest
          imagePullPolicy: Always
          command: ["airflow", "scheduler"]
          envFrom:
            - configMapRef:
                name: airflow-config
            - secretRef:
                name: airflow-secret
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"