# El configmap nos sirce para almacenar variables de entorno no sensibles de la aplicación

# apiVersion = Version de la API de Kubernetes que es v1 por defectoa
# kind = Tipo de recurso que se va a crear, en este caso un configMap
# metadata = Informacion descriptiva del recurso, como el nombre y el namespace donde vive
# name = Nombre del ConfigMap que agrupa las variables de configuración
# namespace = Namespace donde se va a crear (reservainteligente)

# data = Incluimos todas las configs importantes de la apliacion como puertos y denas

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: reservainteligente
data:
  AWS_COGNITO_REGION: "us-east-2"
  AWS_COGNITO_USER_POOL_ID: "us-east-2_72geNIkP2"
  AWS_COGNITO_CLIENT_ID: "341rr52jt9s0291t3aoe9cqdsa"

  DATABASE_TYPE: "mongodb"

  DATABASE_USER: "postgres"
  DATABASE_NAME: "restaurantes_db"
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"

  MONGODB_DB_NAME: "reserva_inteligente"
  MONGODB_URI: "mongodb://mongo-service:27017"

  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  ENVIRONMENT: "development"
  PYTHONPATH: "/src"

  JWT_ALGORITHM: "HS256"
  JWT_EXPIRATION_HOURS: "24"