apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: reservainteligente
type: Opaque
stringData:
  # AWS
  AWS_ACCESS_KEY_ID: "TU_ACCESS_KEY"
  AWS_SECRET_ACCESS_KEY: "TU_SECRET_KEY"
  COGNITO_CLIENT_SECRET: "TU_COGNITO_SECRET"

  # Admin codes
  ADMIN_REGISTRATION_CODE: "TU_ADMIN_REGISTRATION_CODE"
  MASTER_ADMIN_CODE: "TU_MASTER_ADMIN_CODE"

  # PostgreSQL
  DATABASE_PASSWORD: "TU_DB_PASSWORD"
  DATABASE_URL: "postgresql://postgres:TU_DB_PASSWORD@postgres-service:5432/restaurantes_db"

  # Mongo
  MONGODB_URI: "mongodb://mongo-service:27017"

  # JWT
  JWT_SECRET_KEY: "TU_JWT_SECRET_KEY"

  # Neo4J
  NEO4J_PASSWORD: "TU_NEO4J_PASSWORD"

