apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: reservainteligente
type: Opaque
stringData:
  # AWS
  AWS_ACCESS_KEY_ID: "TU_ACCESS_KEY"
  AWS_SECRET_ACCESS_KEY: "TU_SECRET_KEY"
  COGNITO_CLIENT_SECRET: "TU_COGNITO_SECRET"

  # Admin codes
  ADMIN_REGISTRATION_CODE: "lebronisthegoat"
  MASTER_ADMIN_CODE: "iwillbegreatdontgiveup"

  # PostgreSQL
  DATABASE_PASSWORD: "MySecurePass123!"
  DATABASE_URL: "postgresql://postgres:MySecurePass123!@postgres-service:5432/restaurantes_db"

  # Mongo
  MONGODB_URI: "mongodb://mongo-service:27017"

  # JWT
  JWT_SECRET_KEY: "mi-clave-secreta-muy-segura-2024-base-datos-2"
