apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: reservainteligente
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "REPLACE_WITH_AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "REPLACE_WITH_AWS_SECRET_ACCESS_KEY"
  COGNITO_CLIENT_SECRET: "REPLACE_WITH_COGNITO_CLIENT_SECRET"
  ADMIN_REGISTRATION_CODE: "REPLACE_WITH_ADMIN_REGISTRATION_CODE"
  MASTER_ADMIN_CODE: "REPLACE_WITH_MASTER_ADMIN_CODE"
  DATABASE_PASSWORD: "REPLACE_WITH_DATABASE_PASSWORD"
  DATABASE_URL: "postgresql://postgres:REPLACE_WITH_DATABASE_PASSWORD@postgres-service:5432/restaurantes_db"
  JWT_SECRET_KEY: "REPLACE_WITH_JWT_SECRET_KEY"
