apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: reservainteligente
spec:
  replicas: 3
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: ghcr.io/chris124v/reserva_inteligente-search-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: ELASTICSEARCH_URL
              value: "http://elasticsearch:9200"
            - name: API_SERVICE_URL
              value: "http://api-service:80"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
